version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: eutc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eutc_db
      MYSQL_USER: eutc_user
      MYSQL_PASSWORD: eutc_password
    ports:
      - "3303:3306"
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data: